version: '3.8'

services:
  # For development, we'll just run the databases in Docker
  # and run the apps locally for hot reloading
  
  postgres:
    ports:
      - "5432:5432"
  
  redis:
    ports:
      - "6379:6379"
  
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"